class myplace::install::developmentmodules {
    myplace::mod{'admin-tool-integration': version=>'11.0'}
    myplace::mod{'admin-tool-strathcleanup': version=>'1.0'}
    myplace::mod{'assign-assignfeedback-strathnotices': version=>'3.0'}
    myplace::mod{'assign-assignsubmission-strathfm': version=>'6.0'}
#    myplace::mod{'assignsubmission-estream/vendor/b2016022600'}
#    myplace::mod{'atto-fontfamily/vendor/b2015051500'}
#    myplace::mod{'atto-morebackcolors/vendor/b2015081000'}
#    myplace::mod{'atto-morefontcolors/vendor/b2016010600'}
#    myplace::mod{'atto-planetestream/vendor/b2016022600'}
    myplace::mod{'auth-pegasus': version=>'3.2'}
    myplace::mod{'auth-shibexternal': version=>'3.5'}
#    myplace::mod{'block-attendance/vendor/b2016050900'}
    myplace::mod{'block-strathcombillboard': version=>'1.2'}
    myplace::mod{'block-crtool': version=>'7.0'}
    myplace::mod{'block-liblinks': version=>'7.0'}
#    myplace::mod{'block-kortext/vendor/b2014120100'}
    myplace::mod{'block-mycoursework': version=>'8.1'}
    myplace::mod{'block-mygroups': version=>'6.0'}
#    myplace::mod{'block-progress/vendor/b2016050100'}
    myplace::mod{'block-staff_list': version=>'1.1'}
    myplace::mod{'block-strathcomnews': version=>'9.0'}
    myplace::mod{'block-strath_coursetabs': version=>'8.0'}
    myplace::mod{'block-strathevents': version=>'2.0'}
    myplace::mod{'block-strathwebdrive': version=>'3.0'}
    myplace::mod{'block-strathtimetable': version=>'7.0'}
    myplace::mod{'block-targetedhtml': version=>'2.1'}
    myplace::mod{'block-welcome_staff': version=>'6.0'}
    myplace::mod{'core-data': version=>'3.3', install_dir=>'data'}
    myplace::mod{'courseformat-accordion': version=>'4.0'}
    myplace::mod{'courseformat-coursezero': version=>'3.0'}
    myplace::mod{'courseformat-semester': version=>'4.0'}
    myplace::mod{'enrol-strathanysession': version=>'6.1'}
    myplace::mod{'enrol-strathcriteria': version=>'10.0'}
    myplace::mod{'enrol-strathcurrentsession': version=>'6.1'}
    myplace::mod{'enrol-strathds': version=>'4.0'}
    myplace::mod{'enrol-strathopenaccess': version=>'2.1'}
    myplace::mod{'enrol-strathpdp': version=>'10.0'}
    myplace::mod{'enrol-strathprofile': version=>'6.2'}
    myplace::mod{'enrol-strathprofilegroups': version=>'10.0'}
    myplace::mod{'enrol-strathprogramme': version=>'10.0'}
#    myplace::mod{'filter-planetestream/vendor/b2016022600'}
    myplace::mod{'filter-strathkeywords': version=>'3.0'}
    myplace::mod{'grade-export-xls_strath': version=>'2.0'}
    myplace::mod{'grade-import_strathcsv': version=>'1.0'}
    myplace::mod{'gradereport-strathblindusers': version=>'2.0'}
    myplace::mod{'gradereport-strathgb': version=>'2.0'}
    myplace::mod{'grade-export-xls_marksreturn': version=>'2.0'}
#    myplace::mod{'local-ltiprovider/vendor/b2016020100'}
#    myplace::mod{'local-mobile/vendor/b2015111108'}
#    myplace::mod{'local-nagios/vendor/b2015070300'}
    myplace::mod{'local-strath': version=>'3.0'}
    myplace::mod{'local-strathast': version=>'6.0'}
    myplace::mod{'local-strathbulkenrol': version=>'2.0'}
    myplace::mod{'local-strathcoursecache': version=>'3.0'}
    myplace::mod{'local-strathcoursecreate': version=>'2.0'}
    myplace::mod{'local-strathcoursedata': version=>'3.0'}
    myplace::mod{'local-strathcourseselect': version=>'4.0'}
    myplace::mod{'local-strathenrol': version=>'11.0'}
    myplace::mod{'local-strathfm': version=>'5.0'}
    myplace::mod{'local-strathotherusers': version=>'4.0'}
    myplace::mod{'local-strathseams': version=>'1.0'}
    myplace::mod{'local-strathserverstatus': version=>'3.0'}
    myplace::mod{'local-strathuserselect': version=>'4.0'}
    myplace::mod{'local-strathvip': version=>'2.4'}
    myplace::mod{'local-strathws': version=>'3.0'}
#    myplace::mod{'logstore-xapi/vendor/b2016012900'}
    myplace::mod{'message-strathpegasus': version=>'1.0'}
#    myplace::mod{'mod-attendance/vendor/b2016031501'}
#    myplace::mod{'mod-certificate/vendor/b2015111601'}
    myplace::mod{'certificate-A4_embedded_WAS': version=>'1.0', install_dir=>'mod/certificate/type/'}
#    myplace::mod{'mod-forumng/vendor/b2016051000'}
#    myplace::mod{'mod-groupselect/vendor/b2016021200'}
    myplace::mod{'mod-liblinks': version=>'6.0'}
    myplace::mod{'mod-multichoice': version=>'3.0'}
#    myplace::mod{'mod-oublog/vendor/b2016051000'}
    myplace::mod{'mod-peerassessment': version=>'6.0'}
    myplace::mod{'mod-mycoursework': version=>'8.0'}
    myplace::mod{'mod-strathclasscat': version=>'4.0'}
    myplace::mod{'mod-strathcom': version=>'9.0'}
    myplace::mod{'mod-strathresourcelist': version=>'6.0'}
#    myplace::mod{'mod-turnitintooltwo/vendor/b2016072601'}
#    myplace::mod{'plagiarism-turnitin/vendor/b2016072601'}
#    myplace::mod{'quiz-cbmgrades/vendor/b2014082500'}
    myplace::mod{'report-groups': version=>'3.0'}
#    myplace::mod{'report-customsql/vendor/b2015071000'}
    myplace::mod{'report-sbsforum': version=>'1.1'}
    myplace::mod{'repository-hdrive': version=>'3.0'}
#    myplace::mod{'repository-planetestream/vendor/b2016022600'}
#    myplace::mod{'tinymce-planetestream/vendor/b2016022600'}
    myplace::mod{'theme-strathclyde': version=>'7.0'}
    myplace::mod{'tool-strathvleaudit': version=>'1.0'}

}
